# Generated by Django 4.0 on 2021-12-22 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lib_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_issued', models.IntegerField(default=0)),
                ('books_added', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib_app.profile')),
            ],
        ),
    ]
