# Generated by Django 4.0 on 2021-12-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0007_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_link',
            field=models.TextField(default='static/default_files/default_book_cover_2015.jpg', null=True),
        ),
    ]
