# Generated by Django 4.0 on 2021-12-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Librarian',
        ),
    ]
