# Generated by Django 4.0 on 2022-01-09 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lib_app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lib_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='librarian.libdata'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AddField(
            model_name='issue',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_app.book'),
        ),
        migrations.AddField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
