# Generated by Django 4.0 on 2021-12-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0003_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='brating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='book',
            name='bratings',
            field=models.IntegerField(default=0),
        ),
    ]
