# Generated by Django 4.0 on 2022-01-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0004_alter_review_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
