# Generated by Django 4.0 on 2021-12-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0005_profile_hostel_profile_phone_number_profile_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_link',
            field=models.TextField(null=True),
        ),
    ]
