# Generated by Django 4.0 on 2021-12-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0006_alter_book_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(),
        ),
    ]
