# Generated by Django 4.0 on 2021-12-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0007_alter_book_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='denied',
            name='uid',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='uid',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='issued',
            name='uid',
            field=models.TextField(null=True),
        ),
    ]
