# Generated by Django 4.0 on 2021-12-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0008_denied_uid_issue_uid_issued_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
    ]
