# Generated by Django 4.0 on 2021-12-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0009_book_rating_book_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=5),
        ),
    ]
