# Generated by Django 4.0 on 2021-12-22 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_remove_libdata_user'),
        ('lib_app', '0010_book_lib_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='lib_data',
        ),
        migrations.AddField(
            model_name='profile',
            name='lib_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='librarian.libdata'),
        ),
    ]
