# Generated by Django 4.0 on 2021-12-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0011_returned_profile_merit_profile_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='returned',
            name='username',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
