# Generated by Django 4.0 on 2021-12-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0011_remove_book_lib_data_profile_lib_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='brating',
            field=models.FloatField(default=5),
        ),
    ]
