# Generated by Django 4.0 on 2021-12-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0015_renew'),
    ]

    operations = [
        migrations.AddField(
            model_name='renew',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
