# Generated by Django 4.0 on 2021-12-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0016_renew_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
